pipeline {
    agent any

    tools {
        jdk 'JDK17'
    }

    stages {
        stage('Checkout SCM') {
            steps {
                script {
                    checkout scm
                }
            }
        }

        stage('Load Credentials') {
            steps {
                script {
                    withCredentials([
                        string(credentialsId: 'BACKEND_MESSAGE', variable: 'MATTERMOST_WEBHOOK_URL'),
                        string(credentialsId: 'DB_URL', variable: 'DB_URL'),
                        string(credentialsId: 'DB_USER', variable: 'DB_USER'),
                        string(credentialsId: 'DB_PASSWORD', variable: 'DB_PASSWORD'),
                        string(credentialsId: 'JWT_SECRET_KEY', variable: 'JWT_SECRET_KEY'),
                        string(credentialsId: 'NAVER_CLIENT_ID', variable: 'NAVER_CLIENT_ID'),
                        string(credentialsId: 'NAVER_CLIENT_SECRET', variable: 'NAVER_CLIENT_SECRET'),
                        string(credentialsId: 'GOOGLE_CLIENT_ID', variable: 'GOOGLE_CLIENT_ID'),
                        string(credentialsId: 'GOOGLE_CLIENT_SECRET', variable: 'GOOGLE_CLIENT_SECRET'),
                        string(credentialsId: 'DOCKER_CONTAINER_NAME', variable: 'DOCKER_CONTAINER_NAME'),
                        string(credentialsId: 'DOCKER_IMAGE_NAME', variable: 'DOCKER_IMAGE_NAME'),
                        string(credentialsId: 'DOCKER_PORT', variable: 'DOCKER_PORT')
                    ]) {
                        env.MATTERMOST_WEBHOOK_URL = MATTERMOST_WEBHOOK_URL
                        env.DB_URL = DB_URL
                        env.DB_USER = DB_USER
                        env.DB_PASSWORD = DB_PASSWORD
                        env.JWT_SECRET_KEY = JWT_SECRET_KEY
                        env.NAVER_CLIENT_ID = NAVER_CLIENT_ID
                        env.NAVER_CLIENT_SECRET = NAVER_CLIENT_SECRET
                        env.GOOGLE_CLIENT_ID = GOOGLE_CLIENT_ID
                        env.GOOGLE_CLIENT_SECRET = GOOGLE_CLIENT_SECRET
                        env.DOCKER_CONTAINER_NAME = DOCKER_CONTAINER_NAME 
                        env.DOCKER_IMAGE_NAME = DOCKER_IMAGE_NAME
                        env.DOCKER_PORT = DOCKER_PORT
                    }
                }
            }
        }

        stage('Build with Gradle') {
            steps {
                dir('backend') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('backend') {
                        sh 'docker build -t ${DOCKER_IMAGE_NAME} .'
                    }
                }
            }
        }

        stage('Deploy Backend') {
            steps {
                script {
                    sh """
                    docker stop ${DOCKER_CONTAINER_NAME} || true
                    docker rm ${DOCKER_CONTAINER_NAME} || true
                    docker run -d --name ${DOCKER_CONTAINER_NAME} --network starbooks \\
                        -p ${DOCKER_PORT}:${DOCKER_PORT} \\
                        -e DB_URL=${DB_URL} \\
                        -e DB_USER=${DB_USER} \\
                        -e DB_PASSWORD=${DB_PASSWORD} \\
                        -e JWT_SECRET_KEY=${JWT_SECRET_KEY} \\
                        -e NAVER_CLIENT_ID=${NAVER_CLIENT_ID} \\
                        -e NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET} \\
                        -e GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} \\
                        -e GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} \\
                        ${DOCKER_IMAGE_NAME}
                    """
                }
            }
        }
    }

    post {
        success {
            script {
                def jsonMessage = """{
                    "attachments": [{
                        "text": "**✅ Backend Build 성공**\\n\\n- 상태: SUCCESS\\n\\n- [🔗 상세 정보](${env.BUILD_URL})",
                        "color": "#00FF00"
                    }]
                }"""

                sh """
                echo '${jsonMessage}' > mattermost_payload.json
                curl -X POST -H "Content-Type: application/json" --data @mattermost_payload.json '${MATTERMOST_WEBHOOK_URL}'
                rm -f mattermost_payload.json
                """
            }
        }
        failure {
            script {
                def jsonMessage = """{
                    "attachments": [{
                        "text": "**❌ Backend Build 실패**\\n\\n- 상태: FAILURE\\n\\n- [🔗 상세 정보](${env.BUILD_URL}/console)",
                        "color": "#FF0000"
                    }]
                }"""

                sh """
                echo '${jsonMessage}' > mattermost_payload.json
                curl -X POST -H "Content-Type: application/json" --data @mattermost_payload.json '${MATTERMOST_WEBHOOK_URL}'
                rm -f mattermost_payload.json
                """
            }
        }
    }
}
