server:
  port: 9090

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${}com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: ${GOOGLE_CLIENT_ID}
#            client-secret: ${GOOGLE_CLIENT_SECRET}
#            scope:
#              - openid
#              - profile
#              - email
#            redirect-uri: "{baseUrl}/login/oauth2/code/google"
#            authorization-grant-type: authorization_code
#          naver:
#            client-id: ${NAVER_CLIENT_ID}
#            client-secret: ${NAVER_CLIENT_SECRET}
#            scope:
#              - name
#              - email
#              - profile
#            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
#            authorization-grant-type: authorization_code
#        provider:
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize
#            token-uri: https://nid.naver.com/oauth2.0/token
#            user-info-uri: https://openapi.naver.com/v1/nid/me
#            user-name-attribute: response

jwt:
  secret: ${JWT_SECRET_KEY}
  accessToken-expiration: 1800000
  refreshToken-expiration: 1209600000
  oauth-sign-up-expiration: 600000

#cloud:
#  aws:
#    credentials:
#      accessKey: your_access_key #
#      secretKey: your_secret_key #
#    s3:
#      bucket: your_s3_bucket_name
#    region:
#      static: ap-northeast-2
